# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    continuationIndentSize: 8
  ParameterListWrapping:
    indentSize: 8
  NoWildcardImports:
    active: false

style:
  ForbiddenComment:
    active: false
  WildcardImport:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*', 'org.gradle.kotlin.dsl.*']